### ISSUE TITLE
Nano++

### ISSUE THREAD

**Issue by danboid** [74hc595/68k-nano#5]
This is one of the most interesting homebrew computers I've ever seen, very cool project! I found it via the Fuzix web site. 

If you can design a better one of these that has video output and a couple of joystick ports I'd definitely want to build one.

Have you considered the possibility of using software defined video output like on the Uzebox or the rbox?

https://uzebox.org/

https://rossumblog.com/2010/06/10/rbox-a-diy-32-bit-game-console-for-the-price-of-a-latte/

**Comment by 74hc595** [comment]
I started working one about 3 years ago and got pretty far before putting it on hold. I can’t promise it’ll ever be finished, I might publish my work in progress design someday…

Check out my Amethyst project for an example of software defined video. Very similar hardware as the Uzebox but generates color using composite artifacting instead of an expensive encoder chip.

**Comment by danboid** [comment]
I hope you do fnd the time to do another 68K based computer.

There is now the Uzebox Omega which doesn't require the decoder chip:

https://uzebox.org/wiki/Omega

Thanks
